#!/bin/zsh
# Add photos to the Gallery page.
#
#   tools/gallery-add.sh photo.jpg [more photos…]
#   tools/gallery-add.sh photo.jpg --as 005-my-name     # choose the file name (and so the position)
#
# Each photo gets a web-sized copy in images/gallery/ (max 2000px, for the lightbox)
# and a thumbnail in images/gallery/thumbs/ (max 720px, for the grid).
# The gallery shows photos in file-name order, so a name starting with 000- goes first.
# Photos are only ever made smaller, never enlarged. Uses macOS's built-in `sips`.

set -e
cd "$(dirname "$0")/.."
mkdir -p images/gallery/thumbs

shrink() { # shrink <src> <dest> <max-size> <quality>
  local max=$(sips -g pixelWidth -g pixelHeight "$1" | awk '/pixel(Width|Height)/{ if ($2 > m) m = $2 } END { print m }')
  if (( max > $3 )); then
    sips -s format jpeg -s formatOptions $4 -Z $3 "$1" --out "$2" >/dev/null
  else
    sips -s format jpeg -s formatOptions $4 "$1" --out "$2" >/dev/null
  fi
}

while (( $# > 0 )); do
  src="$1"; shift
  if [[ "$1" == "--as" ]]; then name="$2"; shift 2; else name="${${src:t:r}:l}"; fi
  name="${name// /-}"
  [[ -f "$src" ]] || { echo "Not found: $src" >&2; continue; }
  shrink "$src" "images/gallery/$name.jpg" 2000 74
  shrink "$src" "images/gallery/thumbs/$name.jpg" 720 70
  echo "Added images/gallery/$name.jpg"
done

# Record every thumbnail's size so the gallery can lay out before the photos load.
# (Running the script with no photos just refreshes this list, e.g. after deleting a photo.)
{
  echo "# Generated by tools/gallery-add.sh – thumbnail sizes (width, height) for the Gallery page."
  for f in images/gallery/thumbs/*.jpg(N); do
    sips -g pixelWidth -g pixelHeight "$f" | awk -v n="${f:t}" '/pixelWidth/{w=$2} /pixelHeight/{h=$2} END { printf "%s: [%d, %d]\n", n, w, h }'
  done
} > _data/gallery.yml
